name: Setup Node.js

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Install Node modules
      run: pnpm install
      shell: bash
