name: Renovate

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/renovate.yaml"
      - "renovate.json5"
      - "pnpm-lock.yaml"
      - ".node-version"
  pull_request:
    paths:
      - ".github/workflows/renovate.yaml"
      - "renovate.json5"
      - "pnpm-lock.yaml"
      - ".node-version"
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *" # Avoid exactly 0 minutes because of congestion.

permissions:
  contents: read

env:
  RENOVATE_APP_ID: 239200
  RENOVATE_APP_NAME: ganta-renovate
  RENOVATE_APP_EMAIL: 113839177+ganta-renovate[bot]@users.noreply.github.com

jobs:
  get-target:
    outputs:
      repositories: ${{ steps.target.outputs.repositories }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Installation Access Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ env.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get the target repositories
        id: target
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          printf "repositories=" >> "${GITHUB_OUTPUT}"
          gh api \
            -H "Accept: application/vnd.github+json" \
            --paginate \
            /installation/repositories \
          | jq '.repositories[].full_name' \
          | jq --slurp --compact-output >> "${GITHUB_OUTPUT}"

  renovate:
    needs: [get-target]
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.get-target.outputs.repositories) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Get Installation Access Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ env.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Run self-hosted Renovate
        env:
          # Output debug log in GitHub Actions when debug mode is enabled or on branches other than main
          LOG_LEVEL: ${{ (secrets.ACTIONS_STEP_DEBUG == 'true' || github.ref_name != 'main') && 'debug' || 'info' }}
          # GitHub App configuration
          RENOVATE_USERNAME: "${{ env.RENOVATE_APP_NAME }}[bot]"
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
          RENOVATE_GIT_AUTHOR: "${{ env.RENOVATE_APP_EMAIL }}"
          # Switching processing by branch
          RENOVATE_DRY_RUN: ${{ github.ref_name == 'main' && 'null' || 'full' }}
        run: |
          if [[ ${RENOVATE_DRY_RUN} != "null" ]]
          then
            # Do not load main branch configuration
            export RENOVATE_CONFIG_FILE="renovate.json5"
            # Use current branch configuration
            export RENOVATE_REQUIRE_CONFIG="ignored"
          fi

          ./node_modules/.bin/renovate "${{ matrix.repository }}"
